feat(configuration): allow ignored link pattern
A pattern to links which should be ignored may now be specified via

links.validate.ignorePattern = /some-ignored-pattern/

BREAKING CHANGE

For easier configuration properties has been changed to the following
form

```
// default config
{
  // link validation options: false || object
  validate: {
    ignorePattern: null, // pattern to be ignored when validating dead
links
    failOnError: true // whether to fail with an error if link
validation detects a problem
  },
  // link generate options: false || object
  process: {
    include: null, // layouted || [ tags ... ]
    exclude: null, // [ tags ... ]
    overrideRefs: true // if heading refs should be re-generated
  },
  logLevel: 'default' // logging level with which to output data
}
```

Closes #3